version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
      
    working_directory: /go/src/github.com/stn/grpc-helloworld-bazel
    steps:
      - checkout

      - run:
          name: "Enforce Go Formatted Code"
          command: "! go fmt ./... 2>&1 | read"

